version: '3.8'

services:
  typespec-dev:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    container_name: typespec-dev
    image: typespec-dev
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/app
      - ./src/tsp-output:/app/tsp-output
      - ./src/node_modules:/app/node_modules
    ports:
      - "6500:6500"
    environment:
      - NODE_ENV=development
    working_dir: /app
    stdin_open: true
    tty: true  # Permite mantener el contenedor corriendo
    privileged: true # Solo si necesitas capacidades especiales